<?php

function payroll_schema() {
  $schema['payroll'] = array(
    'fields' => array(
      'id'=>array(
        'type'=>'serial',
        'not null' => TRUE,
      ),
      'name'=>array(
      'type' => 'varchar',
      'length' => 40,
      'not null' => TRUE,
      ),

       'employee_id'=>array(
        'type' => 'varchar',
        'length' => 40,
        'not null' => TRUE,
      ),

    ),
    'primary key' => array('id'),
  );

  return $schema;
}